version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Jarmos-san"
    commit-message:
      prefix: "🔀"

- package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Jarmos-san"
    commit-message:
      prefix: "🔀"
