version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Jarmos-san"
    commit-message:
      - prefix: ":twisted_rightwards_arrows:"
