version: 2
updates:

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "🔀"
      labels: ["github-actions", "automerge"]
      target-branch: "dev"

    - package-ecosystem: "gitsubmodules"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "🔀"
      labels: ["submodule", "automerge"]
      target-branch: "dev"


