version: 2
updates:
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
    commit-message:
        prefix: "🔀"
    labels:
        - "automerge"
        - "GitHub Actions"
    target-branch: "dev"

    package-ecosystem: "gitsubmodules"
    directory: "/"
    schedule:
        interval: "daily"
    commit-message:
        prefix: "🔀"
    labels:
        - "automerge"
        - "submodules"
    target-branch: "dev"
