version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
    assignees:
      - "Jarmos-san"
    commit-message:
      prefix: "🔀"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Kolkata"
    assignees:
      - "Jarmos-san"
    commit-message:
      prefix: "🔀"
    target-branch: "dev"
