# Post Processing Settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirects from old site to new one
[[redirects]]
from = "https://jarmos.netlify.app/*"
to = "https://jarmos.netlify.app/posts/*"
