blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Jarmos-san/blog/discussions
    about: Please ask and answer questions here.
  - name: Report Issues and/or Bugs
    url: https://github.com/Jarmos-san/blog/issues
    about: Please report security vulnerabilities here.
