backend:
  # Comment when in production & uncomment when developing locally.
  # name: test-repo
  # Comment this line while developing locally & uncomment when on production.
  name: git-gateway
  branch: dev

media_folder: "static/covers"
public_folder: "/covers"

publish_mode: editorial_workflow

site_url: https://jarmos.netlify.app

show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: 'posts'
    label: 'Articles'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
