backend:
  # Comment when in production & uncomment when developing locally.
  # name: test-repo
  # Comment this line while developing locally & uncomment when on production.
  name: git-gateway
  branch: dev

media_folder: "static/covers"
public_folder: "/covers"

media_library:
  name: cloudinary
  config:
    cloud_name: jarmos
    api_key: 426236226171183

publish_mode: editorial_workflow

site_url: https://jarmos.netlify.app

show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: 'posts'
    label: 'Write Articles'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      # - { label: 'Slug', name: 'slug', }
      - { label: 'Summary', name: 'summary', widget: 'string'}
      # - { label: 'Cover Image' }
      # - { label: 'showtoc', widget: 'boolean' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
