name: Build & Deploy

on:
  push:
    branch:
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Build static content
      run: pelican content -s pelicanconf.py

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      with:
        args: deploy --dir=output --prod

# ! More Actions are available here:
# * https://github.com/South-Paw/action-netlify-deploy
# * https://github.com/netlify/actions

# ! For references, check here:
# * https://marekpukaj.medium.com/build-with-github-actions-host-on-netlify-ebf5fa505616
