# Commented out the whole workflow file to check if Netlify CLI
# works fine or not
on: push
name: CI/CD Build

jobs:
  checkForChanges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check changes in the article
      uses: netlify/actions/diff-includes@master
      with:
        args: blog/output

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --build --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
